apiVersion: clusterclaim.in-cloud.io/v1alpha1
kind: ClusterClaimObserveResourceTemplate
metadata:
  name: default-vault-secret
spec:
  apiVersion: vault.in-cloud.io/v1alpha1
  kind: VaultSecretClaim
  value: |
    metadata:
      labels:
        xcluster.in-cloud.io/name: {{ .ClusterClaim.metadata.name }}
    spec:
      vaultConfigRef:
        name: vault-secret
      clusterRef:
        name: {{ .ClusterClaim.metadata.name }}
      secretsPrefix: clusters/{{ .ClusterClaim.metadata.name }}
      deletionPolicy: Retain
      secretList:
        - name: argocd-admin
          type: generate
          destination:
            path: argocd
            key: admin.password
            hashedKey: admin.passwordBcrypt
          generate:
            length: 16
            hash: bcrypt
        - name: grafana-oidc
          type: copy
          source:
            path: system/dex
            key: staticClient
          destination:
            path: grafana
            key: staticClient
